## Vehicle Routing Problem using OR-Tools
### Import the required libraries

In [1]:
import numpy as np
import pandas as pd
from scipy.spatial.distance import pdist, squareform
import matplotlib.pyplot as plt
import matplotlib as mpl
from ortools.constraint_solver import routing_enums_pb2
from ortools.constraint_solver import pywrapcp

### Load the problem data from file.
Load the CSV file and store it into a dataframe. Set the <code>coordinates</code> from the <code>x</code> and <code>y</code> columns. Set the <code>demands</code> from the <code>d</code> column.

In [4]:
path = pd.read_csv('D:/Ateneo de Davao/College/4thYear1stSem/Computational Optimization & Decision Making/Applied-Combinatorial-Optimisation-code/lab_6_VRP_OR_TOOLS/X-n200-k36.csv')
path

     Unnamed: 0    x    y   d
0             0    0    0   0
1             1  957  135   0
2             2  149  141  83
3             3    1   96  52
4             4  228  268  73
..          ...  ...  ...  ..
196         196  186  373  66
197         197  300   26  88
198         198   52  204  74
199         199  163  305  70
200         200  135  270  80

[201 rows x 4 columns]

In [13]:
coordinates = path.loc[:, ['x', 'y']]
demands = path.d.values

coordinates.head()

     x    y
0    0    0
1  957  135
2  149  141
3    1   96
4  228  268

#### Set the parameters: capacity, number of vehicles, and $N$.

In [ ]:
# Capacity = 402
# Number of vehicles = 36

#### Compute the distance matrix using <code>squareform</code>.

### Instantiate a routing manager and a model.

### Define the distance callback.

### Define the demand callback.

### Add Constraints
#### Add dimensions related to arcs/weights.

### Set the search strategies
Use the default routing search parameters. Use the <code>PATH_CHEAPEST_ARC</code> as the strategy to look for the first solution.

#### Include Tabu Search as a metaheuristic
Set another attribute in the search parameters using the <code>local_search_metaheuristic</code> object.

### Set the objective function
The objective function minimises the total transportation cost. Thus, the <code>transit_callback_index</code> is passed to the <code>SetArcCostEvaluatorOfAllVehicles</code> function.

### Solve the model
#### Print the solution

In [ ]:
def print_solution(data, manager, routing, solution):
    print(f"Objective: {solution.ObjectiveValue()}")
    max_route_distance = 0
    for vehicle_id in range(n_vehicles):
        if not routing.IsVehicleUsed(solution, vehicle_id):
            continue
        index = routing.Start(vehicle_id)
        plan_output = f"Route for vehicle {vehicle_id}:\n"
        route_distance = 0
        while not routing.IsEnd(index):
            plan_output += f" {manager.IndexToNode(index)} -> "
            previous_index = index
            index = solution.Value(routing.NextVar(index))
            route_distance += routing.GetArcCostForVehicle(
                previous_index, index, vehicle_id
            )
        plan_output += f"{manager.IndexToNode(index)}\n"
        plan_output += f"Distance of the route: {route_distance}m\n"
        print(plan_output)
        max_route_distance = max(route_distance, max_route_distance)
    print(f"Maximum of the route distances: {max_route_distance}m")